### ISSUE TITLE
[FIX] 코인 획득 뷰 수정

### ISSUE THREAD

**Issue by cozytk** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#107]
## 💡 Issue

![Uploading image.png…]()

## 📝  todo

- [ ] 불투명한 뷰가 터치가 안 먹히도록 수정
- [ ] 불투명한 뷰를 터치하면 모달이 없어지게 수정
- [ ] 모달이 내려왔다 올라오는 애니메이션 적용
