### ISSUE TITLE
[FEAT] Core Data 기본 CRUD 구현

### ISSUE THREAD

**Issue by JIW00NG** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#15]
## 💡 Issue

Core Data를 이용하여 기본적인 CRUD 코드를 작성합니다.

## 📝  todo

- [x] Core Data 초기 설정(set up Core Data Stack)
- [x] Data Read from Core Data
- [x] Update Core Data value
- [x] Insert Data to Core Data
- [x] Delete Data from Core Data
