### ISSUE TITLE
[FEAT] 보드 뷰 레이아웃 구현

### ISSUE THREAD

**Issue by Minkyeong-Ko** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#19]
## 💡 Issue

- 뱃지를 보여주는 보드 뷰의 레이아웃을 구현합니다

## 📝  todo

- [x] CollectionView를 사용해서 cell 마다 뱃지 위치를 지정합니다
- [x] 상단에 늘 유지되는 fixed 컴포넌트를 만듭니다
- [x] 보드 개수에 따라 화면을 다르게 보여줍니다
