### ISSUE TITLE
[ADD]

### ISSUE THREAD

**Issue by JIW00NG** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#29]
## 💡 Issue

다음과 같은 화면 요소를 구현할 예정입니다.

![요원선택화면](https://user-images.githubusercontent.com/56468120/204069730-607a893f-3250-4a52-9478-77875a0e812a.png)

## 📝  todo

- [ ] 요원 선택 화면 구현
- [ ] 요원 선택 전 모두 활성화
- [ ] 요원 선택 후 선택된 요원 빼고 모두 비활성화
- [ ] 요원 선택 시 선택된 요원의 설명 표시
- [ ] 요원 선택 후 선택 완료 버튼 활성화
