### ISSUE TITLE
[ADD] 온보딩 화면 구현

### ISSUE THREAD

**Issue by JIW00NG** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#35]
## 💡 Issue

온보딩 화면을 구현할 예정입니다.
온보딩 시작을 하면 이야기를 보는 화면까지 표시하고 이야기가 끝나면 요원 선택화면으로 넘어가도록 개발할 예정입니다.
<img width="586" alt="Screenshot 2022-11-27 at 9 44 47 PM" src="https://user-images.githubusercontent.com/56468120/204135926-053c6acb-d342-4966-a876-f56baf12952e.png">

## 📝  todo

- [ ] 앱 사용 설명서 화면 구현
- [ ] 앱 사용 설명서 이후 이야기 화면 구현
- [ ] 이야기 화면에서 다음 버튼을 누르면 다음 이미지와 다음 대사 표시
- [ ] 이야기 화면에서 스킵버튼을 누르면 모두 스킵하고 바로 요원 선택화면으로 이동
