### ISSUE TITLE
[ADD] 보드 뷰 UI 구현

### ISSUE THREAD

**Issue by Minkyeong-Ko** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#41]
## 💡 Issue

보드 뷰의 UI를 그립니다

<img src="https://user-images.githubusercontent.com/78426896/204438388-9ce8842c-8b09-43c1-ba09-f1ae69f0be1a.png" width="350" />

## 📝  todo

- [x] 이전 스타뱃지 획득 여부 화면 구현
- [x] 뱃지 정보 보여주는 fixed upper 컴포넌트 UI 구현
- [x] 뱃지 지도 여백 등 세부 디자인 조정
