### ISSUE TITLE
[FEAT] 실제 뱃지 획득 구현 및 인터랙션 추가

### ISSUE THREAD

**Issue by Minkyeong-Ko** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#42]
## 💡 Issue

새 뱃지를 받을 때 인터랙션을 보여주고 alert을 띄운다

## 📝  todo

- [x] 코어데이터 전체 뱃지 수 업데이트
- [ ] 투명도 또는 크기를 조절해서 애니메이션 주기
- [x] 애니메이션 끝나면 alert 띄우기
- [x] 스타 뱃지를 얻었다면 alert 후 축하 모달 보여주기 
- [x] 새 뱃지 받는 경우를 detect 하기 (12시 넘어서, 알림을 받아서 ==> 결국 동일)
- [x] 임무 완료 텍스트 추가
