### ISSUE TITLE
[FEAT] 보드 뷰 각종 예외상황 테스트

### ISSUE THREAD

**Issue by Minkyeong-Ko** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#65]
## 💡 Issue

버그가 없도록 각종 시나리오를 테스트 해 보려 합니다

## 📝  todo

- [x] 0개의 뱃지를 받은 경우 인터랙션?
- [x] 125개 넘게 받은 경우?
- [x] 24개에서 4개 받아서 스타 받고 다음 화면 넘어갈 때 어떻게 할 지
- [x] 기타 등등
