### ISSUE TITLE
[ADD] 스토리 메인 뷰 구현

### ISSUE THREAD

**Issue by JIW00NG** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#70]
## 💡 Issue

스토리 메인 뷰를 구현할 예정입니다.

## 📝  todo

- [ ] 스토리 메인 뷰 구현
- [ ] 도입 요원으로 임명한다! 버튼 추가
- [ ] 규칙서 앱 사용 설명서 버튼 추가
