### ISSUE TITLE
[FIX] 사이렌뷰 관련 QA 

### ISSUE THREAD

**Issue by KimDaeSeong8721** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#82]
## 💡 Issue

- 사이렌뷰 관련 QA에서 나온 버그 및 수정사항 반영하기
## 📝  todo

- [x] 사이렌 일시정지 버튼 누르면 사운드 멈추기
- [x] 사이렌 잠금해제 1번 풀고 나면 계속 풀려 있는 문제 해결하기
- [x] 잠금해제뷰 틀린라벨 위치 수정하기
