### ISSUE TITLE
[FIX] 보드 뷰 관련 QA

### ISSUE THREAD

**Issue by Minkyeong-Ko** [DeveloperAcademy-POSTECH/MacC-Team-SecretAgent#83]
## 💡 Issue

QA 에서 나온 수정사항을 반영합니다.

## 📝  todo

- [ ] 드롭다운 위치 조정 -> 이건 합치고 해야 할 것 같아서 스킵하겠습니다
- [x] 스타 종류 순서 수정
- [x] 스타 축하 모달 X 버튼 없애기
- [x] 스타 축하 모달 요원 안맞는 문제 해결
